<?php

namespace BlogiridianBundle\Repository;

/**
 * GaleriaPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaPostRepository extends \Doctrine\ORM\EntityRepository
{
}
