<?php

namespace HomeBundle\Repository;

/**
 * ResultadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoRepository extends \Doctrine\ORM\EntityRepository
{
}
