<?php

namespace HomeBundle\Repository;

/**
 * SedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SedeRepository extends \Doctrine\ORM\EntityRepository
{
}
