<?php

namespace HomeBundle\Repository;

/**
 * TemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaRepository extends \Doctrine\ORM\EntityRepository
{
}
