<?php

namespace HomeBundle\Repository;

/**
 * TestimonioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestimonioRepository extends \Doctrine\ORM\EntityRepository
{
}
