<?php

namespace AppBundle\Repository;

/**
 * GeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralRepository extends \Doctrine\ORM\EntityRepository
{
}
