<?php

namespace AppBundle\Repository;

/**
 * PixelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PixelRepository extends \Doctrine\ORM\EntityRepository
{
}
