<?php

namespace AppBundle\Repository;

/**
 * TextoBigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoBigRepository extends \Doctrine\ORM\EntityRepository
{
}
