<?php

namespace AppBundle\Repository;

/**
 * TipoDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDocRepository extends \Doctrine\ORM\EntityRepository
{
}
