imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    read_from:      '%kernel.root_dir%/../www/'
    write_to:       '%kernel.root_dir%/../www/'
    filters:
       cssrewrite:
           bin: '%kernel.root_dir%/../node_modules/gulp-uglify/node_modules/uglifycss/uglifycss'
       uglifyjs2:
           # the path to the uglifyjs executable
           bin: '%kernel.root_dir%/../node_modules/gulp-uglify/node_modules/uglify-js/bin/uglifyjs'
