carrito:
    resource: "@CarritoBundle/Controller/"
    type:     annotation
    prefix:   /

productos:
    resource: "@ProductosBundle/Controller/"
    type:     annotation
    prefix:   /

servicios:
    resource: "@ServiciosBundle/Controller/"
    type:     annotation
    prefix:   /

marcas:
    resource: "@MarcasBundle/Controller/"
    type:     annotation
    prefix:   /

promociones:
    resource: "@PromocionesBundle/Controller/"
    type:     annotation
    prefix:   /

ofertas:
    resource: "@OfertasBundle/Controller/"
    type:     annotation
    prefix:   /

nosotros:
    resource: "@NosotrosBundle/Controller/"
    type:     annotation
    prefix:   /

translation:
    resource: "@TranslationBundle/Controller/"
    type:     annotation
    prefix:   /

reportes:
    resource: "@ReportesBundle/Controller/"
    type:     annotation
    prefix:   /

pagos_payu:
    resource: "@PagosPayuBundle/Controller/"
    type:     annotation
    prefix:   /

user_iridian:
    resource: "@UserIridianBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

blogiridian:
    resource: "@BlogiridianBundle/Controller/"
    type:     annotation
    prefix:   /

carroiridian:
    resource: "@CarroiridianBundle/Controller/"
    type:     annotation
    prefix:   /

contacto:
    resource: "@ContactoBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    resource: "@HomeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

user_logout:
       path: /logout

