<?php

namespace CarroiridianBundle\Repository;

/**
 * ArchivoInventarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoInventarioRepository extends \Doctrine\ORM\EntityRepository
{
}
