<?php

namespace CarroiridianBundle\Repository;

/**
 * BonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonoRepository extends \Doctrine\ORM\EntityRepository
{
}
