<?php

namespace CarroiridianBundle\Repository;

/**
 * CajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaRepository extends \Doctrine\ORM\EntityRepository
{
}
