<?php

namespace CarroiridianBundle\Repository;

/**
 * ComprabonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprabonoRepository extends \Doctrine\ORM\EntityRepository
{
}
