<?php

namespace CarroiridianBundle\Repository;

/**
 * CompraitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompraitemRepository extends \Doctrine\ORM\EntityRepository
{
}
