<?php

namespace CarroiridianBundle\Repository;

/**
 * ConvenioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConvenioRepository extends \Doctrine\ORM\EntityRepository
{
}
