<?php

namespace CarroiridianBundle\Repository;

/**
 * EstadoEnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoEnvioRepository extends \Doctrine\ORM\EntityRepository
{
}
