<?php

namespace CarroiridianBundle\Repository;

/**
 * EstadoCarritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoCarritoRepository extends \Doctrine\ORM\EntityRepository
{
}
