<?php

namespace CarroiridianBundle\Repository;

/**
 * FiltroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiltroRepository extends \Doctrine\ORM\EntityRepository
{
}
