<?php

namespace CarroiridianBundle\Repository;

/**
 * GaleriaproductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GaleriaproductoRepository extends \Doctrine\ORM\EntityRepository
{
}
