<?php

namespace CarroiridianBundle\Repository;

/**
 * MarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaRepository extends \Doctrine\ORM\EntityRepository
{
}
