<?php

namespace CarroiridianBundle\Repository;

/**
 * OpcionunidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcionunidadRepository extends \Doctrine\ORM\EntityRepository
{
}
