<?php

namespace CarroiridianBundle\Repository;

/**
 * PagoLoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoLoggerRepository extends \Doctrine\ORM\EntityRepository
{
}
