<?php

namespace CarroiridianBundle\Repository;

/**
 * PrecioUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
