<?php

namespace CarroiridianBundle\Repository;

/**
 * TallaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TallaRepository extends \Doctrine\ORM\EntityRepository
{
}
