<?php

namespace CarroiridianBundle\Repository;

/**
 * TCCLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TCCLogRepository extends \Doctrine\ORM\EntityRepository
{
}
