<?php

namespace CarroiridianBundle\Repository;

/**
 * TipoFiltroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFiltroRepository extends \Doctrine\ORM\EntityRepository
{
}
