<?php

namespace CarroiridianBundle\Repository;

/**
 * unidadnegocioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class unidadnegocioRepository extends \Doctrine\ORM\EntityRepository
{
}
