<?php

namespace CarroiridianBundle\Repository;

/**
 * UsoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsoRepository extends \Doctrine\ORM\EntityRepository
{
}
