<?php

namespace CarroiridianBundle\Repository;

/**
 * ValorbonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorbonoRepository extends \Doctrine\ORM\EntityRepository
{
}
