<?php

namespace TranslationBundle\Repository;

/**
 * CampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoRepository extends \Doctrine\ORM\EntityRepository
{
}
