<?php

namespace TranslationBundle\Repository;

/**
 * TraduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraduccionRepository extends \Doctrine\ORM\EntityRepository
{
}
