<?php

namespace PagosPayuBundle\Repository;

/**
 * DatosPayuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosPayuRepository extends \Doctrine\ORM\EntityRepository
{
}
