<?php

namespace PagosPayuBundle\Repository;

/**
 * RepuestaPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepuestaPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
