<?php

namespace ContactoBundle\Repository;

/**
 * TipoconsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoconsultaRepository extends \Doctrine\ORM\EntityRepository
{
}
